packages:
  make:
    install: "true"
    aliases: ""
    eval: ""
  jq:
    install: "true"
    aliases: ""
    eval: ""
  node:
    install: "true"
    aliases: ""
    eval: ""
  perl:
    install: "true"
    aliases: ""
    eval: "perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5"
  neovim:
    install: "true"
    aliases:
      vim: nvim
    eval: ""
  stow:
    install: "false"
    aliases: ""
    eval: ""
  ripgrep:
    install: "true"
    aliases: ""
    eval: ""
  fd:
    install: "true"
    aliases: ""
    eval: ""
  fzf:
    install: "true"
    aliases: ""
    eval: "fzf --zsh"
  bat:
    install: "true"
    aliases:
      cat: "bat --paging=never"
    eval: ""
  git-delta:
    install: "true"
    aliases: ""
    eval: ""
  eza:
    install: "true"
    aliases:
      ls: "eza --color=always --group-directories-first --icons"
      ll: "eza -la --icons --octal-permissions --group-directories-first --icons"
      l: "eza -bGF --header --git --color=always --group-directories-first --icons"
      llm: "eza -lbGd --header --git --sort=modified --color=always --group-directories-first --icons"
      la: "eza --long --all --group --group-directories-first"
      lx: "eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale --color=always --group-directories-first --icons"
      lS: "eza -1 --color=always --group-directories-first --icons"
      lt: "eza --tree --level=2 --color=always --group-directories-first --icons"
      l.: "eza -a | grep -E '^\\.'"
    eval: ""
  tlrc:
    install: "true"
    aliases: ""
    eval: ""
  thefuck:
    install: "true"
    aliases: ""
    eval: "thefuck --alias"
  zoxide:
    install: "true"
    aliases:
      cd: "z"
    eval: "zoxide init zsh"
  jesseduffield/lazygit/lazygit:
    install: "true"
    aliases:
      lg: "lazygit"
    eval: ""
plugins:
  powerlevel10k:
    install: "true"
    url: "https://github.com/romkatv/powerlevel10k"
    directory: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    aliases: ""
    eval: ""
  zsh-syntax-highlighting:
    install: "true"
    url: "https://github.com/zsh-users/zsh-syntax-highlighting"
    directory: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    aliases: ""
    eval: ""
  zsh-autosuggestions:
    install: "true"
    url: "https://github.com/zsh-users/zsh-autosuggestions"
    directory: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    aliases: ""
    eval: ""
  kickstart.nvim:
    install: "true"
    url: "https://github.com/nvim-lua/kickstart.nvim"
    directory: "~/.config/nvim-kickstart"
    aliases:
      nvim: "NVIM_APPNAME=\"nvim-kickstart\" nvim"
    eval: ""
  OPTIONAL_SET_INSTALL_TO_TRUE_WITH_NO_DIRECTORY_FOR_ADDITIONAL_ALIASES_OR_EVAL_TO_CREATE_MANY:
    install: "false"
    url: ""
    directory: ""
    aliases:
      nvim: "NVIM_APPNAME=\"nvim-YOUR-CONFIG-LOCATION\" nvim"
      aliasexample1: "aliastest1"
      aliasexample2: "aliastest2"
    eval:
      evalexample1: "evaltest1"
      evalexample2: "evaltest2"

